//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwentyFourSevenOfficeOTDS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.24sevenoffice.com/authenticate/v001/authenticate.asmx")]
        public string TwentyFourSevenOfficeOTDS_TwentyFourSevenOffice_Services_Authenticate_Authenticate {
            get {
                return ((string)(this["TwentyFourSevenOfficeOTDS_TwentyFourSevenOffice_Services_Authenticate_Authenticat" +
                    "e"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.24sevenoffice.com/Economy/InvoiceOrder/V001/InvoiceService.asmx")]
        public string TwentyFourSevenOfficeOTDS_TwentyFourSevenOffice_Services_Invoices_InvoiceService {
            get {
                return ((string)(this["TwentyFourSevenOfficeOTDS_TwentyFourSevenOffice_Services_Invoices_InvoiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservices.24sevenoffice.com/CRM/Contact/PersonService.asmx")]
        public string TwentyFourSevenOfficeOTDS_TwentyFourSevenOffice_Services_PersonService_PersonService {
            get {
                return ((string)(this["TwentyFourSevenOfficeOTDS_TwentyFourSevenOffice_Services_PersonService_PersonServ" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.24sevenoffice.com/Client/V001/ClientService.asmx")]
        public string TwentyFourSevenOfficeOTDS_TwentyFourSevenOffice_Services_ClientService_ClientService {
            get {
                return ((string)(this["TwentyFourSevenOfficeOTDS_TwentyFourSevenOffice_Services_ClientService_ClientServ" +
                    "ice"]));
            }
        }
    }
}
