//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TwentyFourSevenOfficeOTDS.TwentyFourSevenOffice.Services.Invoices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InvoiceServiceSoap", Namespace="http://24sevenOffice.com/webservices")]
    public partial class InvoiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOrderSyncListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateInvoicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveInvoicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoiceDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeliveryMethodsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoiceTemplatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaymentMethodsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InvoiceService() {
            this.Url = global::TwentyFourSevenOfficeOTDS.Properties.Settings.Default.TwentyFourSevenOfficeOTDS_TwentyFourSevenOffice_Services_Invoices_InvoiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOrderSyncListCompletedEventHandler GetOrderSyncListCompleted;
        
        /// <remarks/>
        public event GetInvoicesCompletedEventHandler GetInvoicesCompleted;
        
        /// <remarks/>
        public event UpdateInvoicesCompletedEventHandler UpdateInvoicesCompleted;
        
        /// <remarks/>
        public event SaveInvoicesCompletedEventHandler SaveInvoicesCompleted;
        
        /// <remarks/>
        public event GetInvoiceDocumentCompletedEventHandler GetInvoiceDocumentCompleted;
        
        /// <remarks/>
        public event GetDeliveryMethodsCompletedEventHandler GetDeliveryMethodsCompleted;
        
        /// <remarks/>
        public event GetInvoiceTemplatesCompletedEventHandler GetInvoiceTemplatesCompleted;
        
        /// <remarks/>
        public event GetPaymentMethodsCompletedEventHandler GetPaymentMethodsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetOrderSyncList", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetOrderSyncList(InvoiceSyncParameters syncParams) {
            object[] results = this.Invoke("GetOrderSyncList", new object[] {
                        syncParams});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderSyncListAsync(InvoiceSyncParameters syncParams) {
            this.GetOrderSyncListAsync(syncParams, null);
        }
        
        /// <remarks/>
        public void GetOrderSyncListAsync(InvoiceSyncParameters syncParams, object userState) {
            if ((this.GetOrderSyncListOperationCompleted == null)) {
                this.GetOrderSyncListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderSyncListOperationCompleted);
            }
            this.InvokeAsync("GetOrderSyncList", new object[] {
                        syncParams}, this.GetOrderSyncListOperationCompleted, userState);
        }
        
        private void OnGetOrderSyncListOperationCompleted(object arg) {
            if ((this.GetOrderSyncListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderSyncListCompleted(this, new GetOrderSyncListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetInvoices", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvoiceOrder[] GetInvoices(InvoiceSearchParameters searchParams, string[] invoiceReturnProperties, string[] rowReturnProperties) {
            object[] results = this.Invoke("GetInvoices", new object[] {
                        searchParams,
                        invoiceReturnProperties,
                        rowReturnProperties});
            return ((InvoiceOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoicesAsync(InvoiceSearchParameters searchParams, string[] invoiceReturnProperties, string[] rowReturnProperties) {
            this.GetInvoicesAsync(searchParams, invoiceReturnProperties, rowReturnProperties, null);
        }
        
        /// <remarks/>
        public void GetInvoicesAsync(InvoiceSearchParameters searchParams, string[] invoiceReturnProperties, string[] rowReturnProperties, object userState) {
            if ((this.GetInvoicesOperationCompleted == null)) {
                this.GetInvoicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoicesOperationCompleted);
            }
            this.InvokeAsync("GetInvoices", new object[] {
                        searchParams,
                        invoiceReturnProperties,
                        rowReturnProperties}, this.GetInvoicesOperationCompleted, userState);
        }
        
        private void OnGetInvoicesOperationCompleted(object arg) {
            if ((this.GetInvoicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoicesCompleted(this, new GetInvoicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/UpdateInvoices", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvoiceOrder[] UpdateInvoices(InvoiceOrder[] invoices) {
            object[] results = this.Invoke("UpdateInvoices", new object[] {
                        invoices});
            return ((InvoiceOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateInvoicesAsync(InvoiceOrder[] invoices) {
            this.UpdateInvoicesAsync(invoices, null);
        }
        
        /// <remarks/>
        public void UpdateInvoicesAsync(InvoiceOrder[] invoices, object userState) {
            if ((this.UpdateInvoicesOperationCompleted == null)) {
                this.UpdateInvoicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateInvoicesOperationCompleted);
            }
            this.InvokeAsync("UpdateInvoices", new object[] {
                        invoices}, this.UpdateInvoicesOperationCompleted, userState);
        }
        
        private void OnUpdateInvoicesOperationCompleted(object arg) {
            if ((this.UpdateInvoicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateInvoicesCompleted(this, new UpdateInvoicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/SaveInvoices", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvoiceOrder[] SaveInvoices(InvoiceOrder[] invoices) {
            object[] results = this.Invoke("SaveInvoices", new object[] {
                        invoices});
            return ((InvoiceOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveInvoicesAsync(InvoiceOrder[] invoices) {
            this.SaveInvoicesAsync(invoices, null);
        }
        
        /// <remarks/>
        public void SaveInvoicesAsync(InvoiceOrder[] invoices, object userState) {
            if ((this.SaveInvoicesOperationCompleted == null)) {
                this.SaveInvoicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveInvoicesOperationCompleted);
            }
            this.InvokeAsync("SaveInvoices", new object[] {
                        invoices}, this.SaveInvoicesOperationCompleted, userState);
        }
        
        private void OnSaveInvoicesOperationCompleted(object arg) {
            if ((this.SaveInvoicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveInvoicesCompleted(this, new SaveInvoicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetInvoiceDocument", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetInvoiceDocument(InvoiceDocumentSearchParameters Parameters) {
            object[] results = this.Invoke("GetInvoiceDocument", new object[] {
                        Parameters});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceDocumentAsync(InvoiceDocumentSearchParameters Parameters) {
            this.GetInvoiceDocumentAsync(Parameters, null);
        }
        
        /// <remarks/>
        public void GetInvoiceDocumentAsync(InvoiceDocumentSearchParameters Parameters, object userState) {
            if ((this.GetInvoiceDocumentOperationCompleted == null)) {
                this.GetInvoiceDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceDocumentOperationCompleted);
            }
            this.InvokeAsync("GetInvoiceDocument", new object[] {
                        Parameters}, this.GetInvoiceDocumentOperationCompleted, userState);
        }
        
        private void OnGetInvoiceDocumentOperationCompleted(object arg) {
            if ((this.GetInvoiceDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceDocumentCompleted(this, new GetInvoiceDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetDeliveryMethods", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryMethod[] GetDeliveryMethods() {
            object[] results = this.Invoke("GetDeliveryMethods", new object[0]);
            return ((DeliveryMethod[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDeliveryMethodsAsync() {
            this.GetDeliveryMethodsAsync(null);
        }
        
        /// <remarks/>
        public void GetDeliveryMethodsAsync(object userState) {
            if ((this.GetDeliveryMethodsOperationCompleted == null)) {
                this.GetDeliveryMethodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeliveryMethodsOperationCompleted);
            }
            this.InvokeAsync("GetDeliveryMethods", new object[0], this.GetDeliveryMethodsOperationCompleted, userState);
        }
        
        private void OnGetDeliveryMethodsOperationCompleted(object arg) {
            if ((this.GetDeliveryMethodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeliveryMethodsCompleted(this, new GetDeliveryMethodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetInvoiceTemplates", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TemplateModel[] GetInvoiceTemplates() {
            object[] results = this.Invoke("GetInvoiceTemplates", new object[0]);
            return ((TemplateModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceTemplatesAsync() {
            this.GetInvoiceTemplatesAsync(null);
        }
        
        /// <remarks/>
        public void GetInvoiceTemplatesAsync(object userState) {
            if ((this.GetInvoiceTemplatesOperationCompleted == null)) {
                this.GetInvoiceTemplatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceTemplatesOperationCompleted);
            }
            this.InvokeAsync("GetInvoiceTemplates", new object[0], this.GetInvoiceTemplatesOperationCompleted, userState);
        }
        
        private void OnGetInvoiceTemplatesOperationCompleted(object arg) {
            if ((this.GetInvoiceTemplatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceTemplatesCompleted(this, new GetInvoiceTemplatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://24sevenOffice.com/webservices/GetPaymentMethods", RequestNamespace="http://24sevenOffice.com/webservices", ResponseNamespace="http://24sevenOffice.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PaymentMethod[] GetPaymentMethods() {
            object[] results = this.Invoke("GetPaymentMethods", new object[0]);
            return ((PaymentMethod[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentMethodsAsync() {
            this.GetPaymentMethodsAsync(null);
        }
        
        /// <remarks/>
        public void GetPaymentMethodsAsync(object userState) {
            if ((this.GetPaymentMethodsOperationCompleted == null)) {
                this.GetPaymentMethodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentMethodsOperationCompleted);
            }
            this.InvokeAsync("GetPaymentMethods", new object[0], this.GetPaymentMethodsOperationCompleted, userState);
        }
        
        private void OnGetPaymentMethodsOperationCompleted(object arg) {
            if ((this.GetPaymentMethodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentMethodsCompleted(this, new GetPaymentMethodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class InvoiceSyncParameters {
        
        private System.DateTime changedAfterField;
        
        private System.DateTime registeredAfterField;
        
        public InvoiceSyncParameters() {
            this.changedAfterField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime ChangedAfter {
            get {
                return this.changedAfterField;
            }
            set {
                this.changedAfterField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegisteredAfter {
            get {
                return this.registeredAfterField;
            }
            set {
                this.registeredAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class PaymentMethod {
        
        private int idField;
        
        private string nameField;
        
        public PaymentMethod() {
            this.idField = -2147483648;
            this.nameField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class TemplateModel {
        
        private string fileNameField;
        
        private string nameField;
        
        private System.Guid idField;
        
        private string languageField;
        
        private string countryField;
        
        private bool isSystemTemplateField;
        
        private bool isDefaultField;
        
        private System.DateTime modifiedField;
        
        private int[] customersField;
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSystemTemplate {
            get {
                return this.isSystemTemplateField;
            }
            set {
                this.isSystemTemplateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        public int[] Customers {
            get {
                return this.customersField;
            }
            set {
                this.customersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class InvoiceDocumentSearchParameters {
        
        private int invoiceIdField;
        
        private System.Guid templateIdField;
        
        /// <remarks/>
        public int InvoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                this.invoiceIdField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Guid is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'guid' is not supported in this version of the .Net Framework.  Ignoring default='00000000-0000-0000-0000-000000000000' attribute.
        public System.Guid TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class DeliveryMethod {
        
        private int idField;
        
        private string descriptionField;
        
        public DeliveryMethod() {
            this.idField = -2147483648;
            this.descriptionField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class APIException {
        
        private string typeField;
        
        private string messageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class UserDefinedDimension {
        
        private int typeIdField;
        
        private string nameField;
        
        private string valueField;
        
        public UserDefinedDimension() {
            this.typeIdField = -2147483648;
            this.nameField = "";
            this.valueField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class TaxSettings {
        
        private int taxAccountField;
        
        private int taxCodeField;
        
        private decimal taxRateField;
        
        public TaxSettings() {
            this.taxAccountField = -2147483648;
            this.taxCodeField = -2147483648;
            this.taxRateField = ((decimal)(-79228162514264337593543950335m));
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TaxAccount {
            get {
                return this.taxAccountField;
            }
            set {
                this.taxAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class InvoiceRow {
        
        private int productIdField;
        
        private int rowIdField;
        
        private decimal vatRateField;
        
        private decimal priceField;
        
        private string nameField;
        
        private decimal discountRateField;
        
        private decimal quantityField;
        
        private decimal quantityDeliveredField;
        
        private decimal quantityOrderedField;
        
        private decimal quantityRestField;
        
        private decimal costField;
        
        private ChangeState changeStateField;
        
        private int typeGroupIdField;
        
        private short sequenceNumberField;
        
        private bool hiddenField;
        
        private RowType typeField;
        
        private decimal inPriceField;
        
        private System.DateTime accrualDateField;
        
        private int accrualLengthField;
        
        private System.Nullable<bool> accountProjectField;
        
        private bool accountProjectFieldSpecified;
        
        private int projectIdField;
        
        private int departmentIdField;
        
        private string productNoField;
        
        private TaxSettings taxSettingsField;
        
        private UserDefinedDimension[] userDefinedDimensionsField;
        
        public InvoiceRow() {
            this.productIdField = -2147483648;
            this.rowIdField = -2147483648;
            this.vatRateField = ((decimal)(-79228162514264337593543950335m));
            this.priceField = ((decimal)(-79228162514264337593543950335m));
            this.nameField = "";
            this.discountRateField = ((decimal)(-79228162514264337593543950335m));
            this.quantityField = ((decimal)(-79228162514264337593543950335m));
            this.quantityDeliveredField = ((decimal)(-79228162514264337593543950335m));
            this.quantityOrderedField = ((decimal)(-79228162514264337593543950335m));
            this.quantityRestField = ((decimal)(-79228162514264337593543950335m));
            this.costField = ((decimal)(-79228162514264337593543950335m));
            this.changeStateField = ChangeState.None;
            this.typeGroupIdField = -2147483648;
            this.sequenceNumberField = ((short)(-32768));
            this.hiddenField = false;
            this.typeField = RowType.Normal;
            this.inPriceField = ((decimal)(-79228162514264337593543950335m));
            this.accrualDateField = new System.DateTime(0);
            this.accrualLengthField = -2147483648;
            this.projectIdField = -2147483648;
            this.departmentIdField = -2147483648;
            this.productNoField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal VatRate {
            get {
                return this.vatRateField;
            }
            set {
                this.vatRateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal DiscountRate {
            get {
                return this.discountRateField;
            }
            set {
                this.discountRateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal QuantityDelivered {
            get {
                return this.quantityDeliveredField;
            }
            set {
                this.quantityDeliveredField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal QuantityOrdered {
            get {
                return this.quantityOrderedField;
            }
            set {
                this.quantityOrderedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal QuantityRest {
            get {
                return this.quantityRestField;
            }
            set {
                this.quantityRestField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ChangeState.None)]
        public ChangeState ChangeState {
            get {
                return this.changeStateField;
            }
            set {
                this.changeStateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TypeGroupId {
            get {
                return this.typeGroupIdField;
            }
            set {
                this.typeGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "-32768")]
        public short SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Hidden {
            get {
                return this.hiddenField;
            }
            set {
                this.hiddenField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(RowType.Normal)]
        public RowType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal InPrice {
            get {
                return this.inPriceField;
            }
            set {
                this.inPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime AccrualDate {
            get {
                return this.accrualDateField;
            }
            set {
                this.accrualDateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int AccrualLength {
            get {
                return this.accrualLengthField;
            }
            set {
                this.accrualLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> AccountProject {
            get {
                return this.accountProjectField;
            }
            set {
                this.accountProjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountProjectSpecified {
            get {
                return this.accountProjectFieldSpecified;
            }
            set {
                this.accountProjectFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ProductNo {
            get {
                return this.productNoField;
            }
            set {
                this.productNoField = value;
            }
        }
        
        /// <remarks/>
        public TaxSettings TaxSettings {
            get {
                return this.taxSettingsField;
            }
            set {
                this.taxSettingsField = value;
            }
        }
        
        /// <remarks/>
        public UserDefinedDimension[] UserDefinedDimensions {
            get {
                return this.userDefinedDimensionsField;
            }
            set {
                this.userDefinedDimensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum ChangeState {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Edit,
        
        /// <remarks/>
        Delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum RowType {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        TextBold,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Currency {
        
        private decimal rateField;
        
        private short unitField;
        
        private string symbolField;
        
        public Currency() {
            this.rateField = ((decimal)(1m));
            this.unitField = ((short)(1));
            this.symbolField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "1")]
        public decimal Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "1")]
        public short Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Address {
        
        private string streetField;
        
        private string stateField;
        
        private string postalCodeField;
        
        private string postalAreaField;
        
        private string nameField;
        
        private string cityField;
        
        private string countryField;
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalArea {
            get {
                return this.postalAreaField;
            }
            set {
                this.postalAreaField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Addresses {
        
        private Address postField;
        
        private Address deliveryField;
        
        private Address visitField;
        
        private Address invoiceField;
        
        /// <remarks/>
        public Address Post {
            get {
                return this.postField;
            }
            set {
                this.postField = value;
            }
        }
        
        /// <remarks/>
        public Address Delivery {
            get {
                return this.deliveryField;
            }
            set {
                this.deliveryField = value;
            }
        }
        
        /// <remarks/>
        public Address Visit {
            get {
                return this.visitField;
            }
            set {
                this.visitField = value;
            }
        }
        
        /// <remarks/>
        public Address Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class InvoiceOrder {
        
        private int orderIdField;
        
        private int customerIdField;
        
        private string customerNameField;
        
        private string customerDeliveryNameField;
        
        private string customerDeliveryPhoneField;
        
        private Addresses addressesField;
        
        private OrderSlipStateType orderStatusField;
        
        private int invoiceIdField;
        
        private System.DateTime dateOrderedField;
        
        private System.DateTime dateInvoicedField;
        
        private System.DateTime dateChangedField;
        
        private int paymentTimeField;
        
        private string customerReferenceNoField;
        
        private int projectIdField;
        
        private int ourReferenceField;
        
        private System.Nullable<bool> includeVATField;
        
        private string yourReferenceField;
        
        private decimal orderTotalIncVatField;
        
        private decimal orderTotalVatField;
        
        private string invoiceTitleField;
        
        private string invoiceTextField;
        
        private System.DateTime paidField;
        
        private string oCRField;
        
        private string customerOrgNoField;
        
        private Currency currencyField;
        
        private int paymentMethodIdField;
        
        private decimal paymentAmountField;
        
        private int productionManagerIdField;
        
        private int salesOpportunityIdField;
        
        private int typeOfSaleIdField;
        
        private Distributor distributorField;
        
        private DistributionMethod distributionMethodField;
        
        private int departmentIdField;
        
        private int externalStatusField;
        
        private string invoiceEmailAddressField;
        
        private InvoiceRow[] invoiceRowsField;
        
        private APIException aPIExceptionField;
        
        private string productionNumberField;
        
        private System.DateTime deliveryDateField;
        
        private int referenceInvoiceIdField;
        
        private int referenceOrderIdField;
        
        private string referenceNumberField;
        
        private bool skipStockField;
        
        private System.DateTime accrualDateField;
        
        private int accrualLengthField;
        
        private decimal roundFactorField;
        
        private System.Guid invoiceTemplateIdField;
        
        private string vippsNumberField;
        
        private DeliveryMethod deliveryMethodField;
        
        private string deliveryAlternativeField;
        
        private System.Nullable<bool> sendToFactoringField;
        
        private bool sendToFactoringFieldSpecified;
        
        private decimal commissionField;
        
        private UserDefinedDimension[] userDefinedDimensionsField;
        
        private string gLNNumberField;
        
        private int customerDeliveryIdField;
        
        public InvoiceOrder() {
            this.orderIdField = -2147483648;
            this.customerIdField = -2147483648;
            this.customerNameField = "";
            this.customerDeliveryPhoneField = "";
            this.orderStatusField = OrderSlipStateType.Web;
            this.invoiceIdField = -2147483648;
            this.dateOrderedField = new System.DateTime(0);
            this.dateInvoicedField = new System.DateTime(0);
            this.dateChangedField = new System.DateTime(0);
            this.paymentTimeField = -2147483648;
            this.customerReferenceNoField = "";
            this.projectIdField = -2147483648;
            this.ourReferenceField = -2147483648;
            this.yourReferenceField = "";
            this.orderTotalIncVatField = ((decimal)(-79228162514264337593543950335m));
            this.orderTotalVatField = ((decimal)(-79228162514264337593543950335m));
            this.invoiceTitleField = "";
            this.invoiceTextField = "";
            this.paidField = new System.DateTime(0);
            this.oCRField = "";
            this.customerOrgNoField = "";
            this.paymentMethodIdField = -2147483648;
            this.paymentAmountField = ((decimal)(-79228162514264337593543950335m));
            this.productionManagerIdField = -2147483648;
            this.salesOpportunityIdField = -2147483648;
            this.typeOfSaleIdField = -2147483648;
            this.distributorField = Distributor.Default;
            this.distributionMethodField = DistributionMethod.Unchanged;
            this.departmentIdField = -2147483648;
            this.externalStatusField = -2147483648;
            this.invoiceEmailAddressField = "";
            this.productionNumberField = "";
            this.deliveryDateField = new System.DateTime(0);
            this.referenceInvoiceIdField = -2147483648;
            this.referenceOrderIdField = -2147483648;
            this.referenceNumberField = "";
            this.skipStockField = false;
            this.accrualDateField = new System.DateTime(0);
            this.accrualLengthField = -2147483648;
            this.roundFactorField = ((decimal)(-79228162514264337593543950335m));
            this.vippsNumberField = "";
            this.deliveryAlternativeField = "";
            this.commissionField = ((decimal)(-79228162514264337593543950335m));
            this.gLNNumberField = "";
            this.customerDeliveryIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerDeliveryName {
            get {
                return this.customerDeliveryNameField;
            }
            set {
                this.customerDeliveryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CustomerDeliveryPhone {
            get {
                return this.customerDeliveryPhoneField;
            }
            set {
                this.customerDeliveryPhoneField = value;
            }
        }
        
        /// <remarks/>
        public Addresses Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(OrderSlipStateType.Web)]
        public OrderSlipStateType OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int InvoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                this.invoiceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateOrdered {
            get {
                return this.dateOrderedField;
            }
            set {
                this.dateOrderedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateInvoiced {
            get {
                return this.dateInvoicedField;
            }
            set {
                this.dateInvoicedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged {
            get {
                return this.dateChangedField;
            }
            set {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int PaymentTime {
            get {
                return this.paymentTimeField;
            }
            set {
                this.paymentTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CustomerReferenceNo {
            get {
                return this.customerReferenceNoField;
            }
            set {
                this.customerReferenceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int OurReference {
            get {
                return this.ourReferenceField;
            }
            set {
                this.ourReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IncludeVAT {
            get {
                return this.includeVATField;
            }
            set {
                this.includeVATField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string YourReference {
            get {
                return this.yourReferenceField;
            }
            set {
                this.yourReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal OrderTotalIncVat {
            get {
                return this.orderTotalIncVatField;
            }
            set {
                this.orderTotalIncVatField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal OrderTotalVat {
            get {
                return this.orderTotalVatField;
            }
            set {
                this.orderTotalVatField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string InvoiceTitle {
            get {
                return this.invoiceTitleField;
            }
            set {
                this.invoiceTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string InvoiceText {
            get {
                return this.invoiceTextField;
            }
            set {
                this.invoiceTextField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime Paid {
            get {
                return this.paidField;
            }
            set {
                this.paidField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string OCR {
            get {
                return this.oCRField;
            }
            set {
                this.oCRField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CustomerOrgNo {
            get {
                return this.customerOrgNoField;
            }
            set {
                this.customerOrgNoField = value;
            }
        }
        
        /// <remarks/>
        public Currency Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int PaymentMethodId {
            get {
                return this.paymentMethodIdField;
            }
            set {
                this.paymentMethodIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal PaymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ProductionManagerId {
            get {
                return this.productionManagerIdField;
            }
            set {
                this.productionManagerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int SalesOpportunityId {
            get {
                return this.salesOpportunityIdField;
            }
            set {
                this.salesOpportunityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TypeOfSaleId {
            get {
                return this.typeOfSaleIdField;
            }
            set {
                this.typeOfSaleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(Distributor.Default)]
        public Distributor Distributor {
            get {
                return this.distributorField;
            }
            set {
                this.distributorField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(DistributionMethod.Unchanged)]
        public DistributionMethod DistributionMethod {
            get {
                return this.distributionMethodField;
            }
            set {
                this.distributionMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ExternalStatus {
            get {
                return this.externalStatusField;
            }
            set {
                this.externalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string InvoiceEmailAddress {
            get {
                return this.invoiceEmailAddressField;
            }
            set {
                this.invoiceEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceRow[] InvoiceRows {
            get {
                return this.invoiceRowsField;
            }
            set {
                this.invoiceRowsField = value;
            }
        }
        
        /// <remarks/>
        public APIException APIException {
            get {
                return this.aPIExceptionField;
            }
            set {
                this.aPIExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ProductionNumber {
            get {
                return this.productionNumberField;
            }
            set {
                this.productionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ReferenceInvoiceId {
            get {
                return this.referenceInvoiceIdField;
            }
            set {
                this.referenceInvoiceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ReferenceOrderId {
            get {
                return this.referenceOrderIdField;
            }
            set {
                this.referenceOrderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SkipStock {
            get {
                return this.skipStockField;
            }
            set {
                this.skipStockField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime AccrualDate {
            get {
                return this.accrualDateField;
            }
            set {
                this.accrualDateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int AccrualLength {
            get {
                return this.accrualLengthField;
            }
            set {
                this.accrualLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal RoundFactor {
            get {
                return this.roundFactorField;
            }
            set {
                this.roundFactorField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Guid is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'guid' is not supported in this version of the .Net Framework.  Ignoring default='00000000-0000-0000-0000-000000000000' attribute.
        public System.Guid InvoiceTemplateId {
            get {
                return this.invoiceTemplateIdField;
            }
            set {
                this.invoiceTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string VippsNumber {
            get {
                return this.vippsNumberField;
            }
            set {
                this.vippsNumberField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryMethod DeliveryMethod {
            get {
                return this.deliveryMethodField;
            }
            set {
                this.deliveryMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string DeliveryAlternative {
            get {
                return this.deliveryAlternativeField;
            }
            set {
                this.deliveryAlternativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> SendToFactoring {
            get {
                return this.sendToFactoringField;
            }
            set {
                this.sendToFactoringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendToFactoringSpecified {
            get {
                return this.sendToFactoringFieldSpecified;
            }
            set {
                this.sendToFactoringFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
            }
        }
        
        /// <remarks/>
        public UserDefinedDimension[] UserDefinedDimensions {
            get {
                return this.userDefinedDimensionsField;
            }
            set {
                this.userDefinedDimensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string GLNNumber {
            get {
                return this.gLNNumberField;
            }
            set {
                this.gLNNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerDeliveryId {
            get {
                return this.customerDeliveryIdField;
            }
            set {
                this.customerDeliveryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum OrderSlipStateType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Offer,
        
        /// <remarks/>
        Pack,
        
        /// <remarks/>
        Invoiced,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Repeating,
        
        /// <remarks/>
        CollectingOrder,
        
        /// <remarks/>
        Return,
        
        /// <remarks/>
        Distribution,
        
        /// <remarks/>
        Rest,
        
        /// <remarks/>
        ForInvoicing,
        
        /// <remarks/>
        OvertimeRent,
        
        /// <remarks/>
        Confirmed,
        
        /// <remarks/>
        OrderState_Sent,
        
        /// <remarks/>
        Production,
        
        /// <remarks/>
        PaymentReminder,
        
        /// <remarks/>
        OnAccount,
        
        /// <remarks/>
        Lending,
        
        /// <remarks/>
        InvoicedCashAccount,
        
        /// <remarks/>
        InvoicedPack,
        
        /// <remarks/>
        Inactive,
        
        /// <remarks/>
        Hours,
        
        /// <remarks/>
        OrderState_SuperStore,
        
        /// <remarks/>
        Draft,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum Distributor {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Manual,
        
        /// <remarks/>
        Auto,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum DistributionMethod {
        
        /// <remarks/>
        Unchanged,
        
        /// <remarks/>
        Print,
        
        /// <remarks/>
        EMail,
        
        /// <remarks/>
        ElectronicInvoice,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class InvoiceSearchParameters {
        
        private int[] customerIdsField;
        
        private System.DateTime changedAfterField;
        
        private OrderSlipStateType[] orderStatesField;
        
        private int[] invoiceIdsField;
        
        private int[] orderIdsField;
        
        private int[] externalStatusField;
        
        public InvoiceSearchParameters() {
            this.changedAfterField = new System.DateTime(0);
        }
        
        /// <remarks/>
        public int[] CustomerIds {
            get {
                return this.customerIdsField;
            }
            set {
                this.customerIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime ChangedAfter {
            get {
                return this.changedAfterField;
            }
            set {
                this.changedAfterField = value;
            }
        }
        
        /// <remarks/>
        public OrderSlipStateType[] OrderStates {
            get {
                return this.orderStatesField;
            }
            set {
                this.orderStatesField = value;
            }
        }
        
        /// <remarks/>
        public int[] InvoiceIds {
            get {
                return this.invoiceIdsField;
            }
            set {
                this.invoiceIdsField = value;
            }
        }
        
        /// <remarks/>
        public int[] OrderIds {
            get {
                return this.orderIdsField;
            }
            set {
                this.orderIdsField = value;
            }
        }
        
        /// <remarks/>
        public int[] ExternalStatus {
            get {
                return this.externalStatusField;
            }
            set {
                this.externalStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetOrderSyncListCompletedEventHandler(object sender, GetOrderSyncListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderSyncListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderSyncListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetInvoicesCompletedEventHandler(object sender, GetInvoicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvoiceOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvoiceOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateInvoicesCompletedEventHandler(object sender, UpdateInvoicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvoiceOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvoiceOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveInvoicesCompletedEventHandler(object sender, SaveInvoicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvoiceOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvoiceOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetInvoiceDocumentCompletedEventHandler(object sender, GetInvoiceDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetDeliveryMethodsCompletedEventHandler(object sender, GetDeliveryMethodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeliveryMethodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeliveryMethodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryMethod[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryMethod[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetInvoiceTemplatesCompletedEventHandler(object sender, GetInvoiceTemplatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceTemplatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceTemplatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TemplateModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TemplateModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetPaymentMethodsCompletedEventHandler(object sender, GetPaymentMethodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentMethodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentMethodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentMethod[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentMethod[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591